XiaomiStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customer.urls')),
    path('', include('cart.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import *

app_name = 'cart'
urlpatterns = [
    path('cart/', cart_detail, name = 'cart_detail'),
    path('update-cart/', update_cart, name='update_cart'),
    path('buy-now/<int:product_id>/', buy_now, name = 'buy_now'),
    # path('cart-add/<int:product_id>/', cart_add, name = 'cart_add'),
    path('remove-cart/<int:product_id>/', remove_cart, name = 'remove_cart'),
    path('checkout/', checkout, name = 'checkout'),
]

customer/urls.py
from django.urls import path
from customer.views import *

app_name = 'customer'
urlpatterns = [
    path('register/', customer_register, name = 'customer_register'), 
    path('login/', customer_login, name = 'customer_login'),
    path('logout/', customer_logout, name = 'customer_logout'),
    path('my-account/', my_account, name = 'my_account'),
    path('reset-password', reset_password, name ='reset_password'),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'
urlpatterns = [
    path('', index, name = 'index'),
    path('contact/', contact, name = 'contact'),
    path('shop-details/<int:pk>/', shop_details, name = 'shop_details'),
    path('shop-grid/<int:pk>/', shop_grid, name = 'shop_grid'),
    path('search/', search, name = 'search'),
   
]

store/models.py
from django.db import models

# Create your models here.
from unicodedata import category
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone

# Create your models here
class Category(models.Model):
    name = models.CharField(max_length= 150, unique = True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete= models.PROTECT)
    name = models.CharField(max_length= 250)
    price = models.FloatField(default= 0.0)
    image = models.ImageField(upload_to = 'store/img', default = 'store/img/logo.png')
    content = RichTextUploadingField(blank = True, null = True)

    def __str__(self):
        return self.name
    

class Contact(models.Model):
    name = models.CharField(max_length= 100)
    email = models.EmailField(blank = False)
    message = models.TextField(blank = False)

    def __str__(self):
        return self.name

store/views.py
from django.shortcuts import redirect, render, HttpResponse
from store.models import *
from cart.cart import Cart
import re
import json
from django.core.paginator import Paginator, EmptyPage
from django.http import JsonResponse
from django.template.loader import render_to_string




# Create your views here.

def index(request):
    cart = Cart(request)

    list_mi_products = []
    list_mi_note_products = []
    list_poco_products = []
    list_redmi_products = []
    list_redmi_note_products = []
    list_gaming_products = []
    list_all_products = []

    all_products = Product.objects.all().order_by('-price')
    
    # max_value = Product.objects.values_list('price').order_by('-price').last()    

    # Lọc
    categories = Category.objects.all()
    
    
    print(len(all_products))
    mi_products = Product.objects.filter(category_id = 1).order_by('-price')
    mi_note_products = Product.objects.filter(category_id = 2).order_by('-price')
    poco_products = Product.objects.filter(category_id = 3).order_by('-price')
    redmi_products = Product.objects.filter(category_id = 4).order_by('-price')
    redmi_note_products = Product.objects.filter(category_id = 5).order_by('-price')
    gaming_products = Product.objects.filter(category_id = 6).order_by('-price')
    # Lấy ra id của các categories
    list_id_categories  = []
    for name in categories.values_list():
        list_id_categories.append(name[0])
    
    list_id_categories = [0,] + list_id_categories

    # Bỏ các sản phẩm có giá là liên hệ
    for product in mi_products:
        if product.price != "Liênhệ":
            list_mi_products.append(product)

    for product in mi_note_products:
        if product.price != "Liênhệ":
            list_mi_note_products.append(product)

    for product in poco_products:
        if product.price != "Liênhệ":
            list_poco_products.append(product)

    for product in redmi_products:
        if product.price != "Liênhệ":
            list_redmi_products.append(product)
    
    for product in redmi_note_products:
        if product.price != "Liênhệ":
            list_redmi_note_products.append(product)
   
    for product in gaming_products:
        if product.price != "Liênhệ":
            list_gaming_products.append(product)
    
    for product in all_products:
        if product.price != "Liênhệ":
            list_all_products.append(product)

    # # Kiểm tra nếu là AJAX request
    # if request.is_ajax():
    #     products_name_data = [{'name': product.name, 'price': product.price} for product in all_products]
    #     return JsonResponse({
    #         'products': products_name_data,

    #     })
    
    
    return render(request, 'store/index.html', {
        'categories':categories,
        'products_all_10': list_all_products[:10],    
        'products_all_8': list_all_products[:8],
        'list_id_categories':list_id_categories,
        'mi_products':list_mi_products[:8],
        'mi_note_products':list_mi_note_products[:8],
        'poco_products':list_poco_products[:8],
        'redmi_products':list_redmi_products[:8],
        'redmi_note_products':list_redmi_note_products[:8],
        'gaming_products':list_gaming_products[:8],
        'cart':cart,

    })


def shop_grid(request, pk):
    cart = Cart(request)
    categories = Category.objects.all()
    all_products_no_contact = Product.objects.exclude(price__icontains='Liênhệ')
    min_value = Product.objects.exclude(price__icontains='Liênhệ').values_list('price').order_by('price')[0][0]
    max_value = Product.objects.exclude(price__icontains='Liênhệ').values_list('price').order_by('price')[len(all_products_no_contact) - 1][0]
    min_price = float(request.GET.get('min_price', min_value)) 
    max_price = float(request.GET.get('max_price', max_value))
    

    list_products = Product.objects.filter(price__range=(min_price, max_price)).order_by('price')
    products_count = list_products.count()
    if pk == 0: 
        products = Product.objects.all().order_by('name')
    else:
        products = Product.objects.filter(category_id = pk).order_by('name')
    
    # Các sản phẩm nổi bật
    list_feature_products = []
    feature_products = Product.objects.all().order_by('-price')
    for product in feature_products:
        if product.price != "Liênhệ":
            list_feature_products.append(product)


    print("Sản phẩm cuối cùng: %s"  %list_products.last())
    print("Min: %s" %min_price)
    print("Max: %s" %max_price)
    print("Số lượng sản phẩm: %s" %products_count)

    # Phân trang
    page = request.GET.get('page', 1)
    paginator = Paginator(list_products, 15)

    try:
        products_pager = paginator.page(page)
    except EmptyPage:
        products_pager = paginator.page(paginator.num_pages)
    
    return render(request, 'store/shop-grid.html',{
        'categories':categories,
        'products': products_pager,
        'total_products': products_count,
        'feature_products_1': list_feature_products[:3],
        'feature_products_2': list_feature_products[3:6],
        'list_products': list_products,
        'min_value':min_value,
        'max_value':max_value,
        'products_count': products_count,
        'cart':cart,
    })

# from django.http import JsonResponse
# from django.template.loader import render_to_string



def shop_details(request, pk):
    cart = Cart(request)
    categories = Category.objects.all()
    product = Product.objects.get(id = pk)
    id_subcategory = product.category_id


    
    # Hiển thị các sản phẩm liên quan
    related_products = Product.objects.filter(category_id = id_subcategory).exclude(id = pk).order_by('price')
    return render(request, 'store/shop-details.html',{
        'categories':categories,
        'product':product,
        'related_products': related_products[:12],
        'cart':cart
    })

# def shoping_cart(request):
#     categories = Category.objects.all()
#     return render(request, 'store/shoping-cart.html',
#     {
#         'categories':categories,
#     })


def contact(request):
    cart = Cart(request)
    categories = Category.objects.all()
    
    # successful_submit == False
    if request.POST.get('btnSend'):
        
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        # Khởi tạo class Contact
        contact = Contact(name = name, email = email, message = message)
        contact.save()
   
    return render(request, 'store/contact.html',{
        'categories':categories,
        'cart':cart,
    })



def search(request):
    cart = Cart(request)
    categories = Category.objects.all()
    title_search = ''
    if request.GET.get('keyword'):
        keyword = request.GET.get('keyword')
        # loại bỏ khoảng trắng nếu lỡ như có ai đó vô tình thêm khoảng trắng vào ô tìm kiếm
        keyword = re.sub(r'^\s+','', keyword.rstrip()) # rstring nhằm loại bỏ khoảng trắng ở cuối chuỗi
        objects = Product.objects.all().values()
        id_products = []
        for object in objects:
            object['content'] = re.sub(r'<[^<]+?>', '', object['content'])
            if keyword.lower() in object['name'].lower() or keyword.lower() in object['content'].lower():
                id_products.append(object['id'])
        else:
            products = Product.objects.filter(id__in = id_products).order_by('-price')
            title_search = 'CÓ %i SẢN PHẨM PHÙ HỢP VỚI KẾT QUẢ TÌM KIẾM: ' %(len(products)) + keyword
    return render(request, 'store/shop-grid.html',{
    'products':products,
    'title_search':title_search,
    'categories':categories,
    'keyword':keyword,
    'cart':cart,
})

store/templates/store/checkout.html
{% extends 'store/_Master.html' %}
{% load static %}
{% load humanize %}
{% load remove_substr %}
{% block title_tab %}Xiaomi | Checkout{% endblock title_tab %}

{% block main_content %}     

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Checkout</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'store:index' %}">Trang chủ</a>
                            <span>Thanh toán</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
                <h4>Chi tiết thanh toán</h4>
                <form method = "post">
                    {%csrf_token%}
                    <div class="row">
                        <div class="col-lg-5 col-md-5">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <!-- <p>First Name<span>*</span></p>
                                        <input type="text"> -->
                                        <p>{{form_order.first_name.label}}</p>
                                        {{form_order.first_name}}
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>{{form_order.last_name.label}}</p>
                                        {{form_order.last_name}}
                                        <!-- <input type="text"> -->
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p>{{form_order.address.label}}</p>
                                {{form_order.address}}
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>{{form_order.email.label}}</p>
                                        {{form_order.email}}
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        
                                        <p>{{form_order.tel.label}}</p>
                                        {{form_order.tel}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7 col-md-7">
                            <div class="checkout__order">
                                <h4>Đơn hàng</h4>
                                <div class="checkout__order__products">Sản phẩm <span> Giá tiền</span></div>
                                <ul>
                                    {% for item in cart %}
                                        {% with product=item.product %}
                                            <li>{{ product.name|remove_substr:'(Chính Hãng Digiworld)' }} * {{item.quantity}} <span>{{item.total_price_prev_coupon|floatformat:0|intcomma}} đ</span></li>
                                        {% endwith %}
                                    {% endfor %}
                                </ul>
                                <!-- <div class="checkout__order__total">Tổng tiền</div> <span>{% load humanize %}{{ cart.get_total_price|floatformat:0|intcomma }} đ</span></div> -->
                                <div class="checkout__order__total_price">Tổng tiền <span>{% load humanize %}{{ cart.get_total_price|floatformat:0|intcomma }} đ</span></div>
                                <div class="checkout__order__subtotal">Giảm giá <span>{% load humanize %}{{ cart.get_discount|floatformat:0|intcomma }} đ</span></div>
                                <div class="checkout__order__total">Tổng tiền phải trả <span>{% load humanize %}{{ cart.get_final_total_price|floatformat:0|intcomma }} đ</span></div>
                                
                                <div class="checkout__input__checkbox">
                                    <label for="payment">
                                        Kiểm tra thanh toán
                                        <input type="checkbox" id="payment" name = "check">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="checkout__input__checkbox">
                                    <label for="paypal">
                                        Chuyển khoản
                                        <input type="checkbox" id="paypal" name = "transfer_credit">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="checkout__input__checkbox">
                                    <label for="paypal">
                                        Thanh toán khi nhận hàng
                                        <input type="checkbox" id="paypal" name = "cod">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <button type="submit" class="site-btn" name = "btnDatHang" value = "Đặt hàng">Đặt hàng</button>
                            </div>
                        </div>    
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->

{% endblock %}

store/templates/store/contact.html
{% extends 'store/_Master.html' %}
{% load static %}
{% block title_tab %}Xiaomi | Trang liên hệ{% endblock title_tab %}

{% block main_content %}


    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Liên hệ</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'store:index' %}" style="font-size:20px">Trang chủ</a>
                            <span>Liên hệ chúng tôi</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_phone"></span>
                        <h4>Số điện thoại</h4>
                        <p>+01-3-8888-6868</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_pin_alt"></span>
                        <h4>Địa chỉ</h4>
                        <p>122 Nguyễn Lâm, Phường 6, Quận 10, TP HCM.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_clock_alt"></span>
                        <h4>Giờ mở cửa</h4>
                        <p>Từ 9:00 đến 23:00</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_mail_alt"></span>
                        <h4>Email</h4>
                        <p>hello@colorlib.com</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->

    <!-- Map Begin -->
    <div class="map">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.6000256481325!2d106.66095801394538!3d10.765277192329103!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ee8bfd9ba69%3A0x4ff8aaff9c5ef3f9!2zMTIyIE5ndXnhu4VuIEzDom0sIFBoxrDhu51uZyA2LCBRdeG6rW4gMTAsIFRow6BuaCBwaOG7kSBI4buTIENow60gTWluaCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1664960393760!5m2!1svi!2s"
            height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        <div class="map-inside">
            <i class="icon_pin"></i>
            <div class="inside-widget">
                <h4>TPHCM</h4>
                <ul>
                    <li>Số điện thoại: +12-345-6789</li>
                    <li>122 Nguyễn Lâm, Phường 6, Quận 10, TP HCM.</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Map End -->

    <!-- Contact Form Begin -->
    
    <div class="contact-form spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact__form__title">
                        <h2>Leave Message</h2>
                    </div>
                </div>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <input type="text" class="form-control" placeholder="Nhập tên" name = 'name'>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <input type="email" class="form-control" placeholder="Nhập email" name = 'email'>
                    </div>
                    <div class="col-lg-12 text-center">
                        <textarea  rows="6" class="form-control" placeholder="Nhập nội dung" name = 'message'></textarea>
                        <button type="button" class="site-btn" name = "btnSend" value="Send Message">GỬI THƯ</button>
                    </div>
                </div>
            </form>
        </div>  
    </div>
    <!-- Contact Form End -->

    
{% endblock %}

store/templates/store/login.html
{% extends 'store/_Master.html' %}
{% load static %}
{% block title_tab %}Xiaomi | Checkout{% endblock title_tab %}

{% block main_content %}    

<div class="col-lg-6">               
    <form method = "post">
        {%csrf_token%}
        <div class="login-form">
            <div class="row">
                <div class="col-md-12">
                    <label>E-mail</label>
                    <!--Làm việc trực tiếp trên html-->
                    <input class="form-control" type="text" placeholder="Email" name="email"> 
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <label>Mật khẩu</label>
                    <input class="form-control" type="password" placeholder="Mật khẩu" name = "mat_khau">
                </div>
            </div>   
                
            <div class="col-md-6">
                <a href="{% url 'customer:reset_password' %}" style="text-decoration: underline; color:blue; font-size: 20px;">Quên mật khẩu?</a>
            </div><br>
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-outline-primary" name = "btnDangNhap" value = "Đăng nhập">Đăng nhập</button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

store/templates/store/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

store/templates/store/shop-details.html
{% extends 'store/_Master.html' %}
{% load static %}
{% load humanize %}
{% load remove_substr %}
{% block title_tab %}Xiaomi | Chi tiết sản phẩm {% endblock title_tab %}

{% block main_content %}     


    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <div class="breadcrumb__option">
                            <a href="{% url 'store:index' %}" style="font-size:20px">Trang chủ</a>
                            <a href="{% url 'store:shop_grid' 0 %}" style="font-size:20px">Cửa hàng</a>
                            <span style="font-size:20px">Chi tiết sản phẩm</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Details Section Begin -->
    <section class="product-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__pic">
                        <div class="product__details__pic__item">
                            <img class="product__details__pic__item--large"
                                src="img/product/details/product-details-1.jpg" alt="">
                        </div>
                        <div class="product__details__pic__slider owl-carousel">
                            <img data-imgbigurl="img/product/details/product-details-2.jpg"
                                src="img/product/details/thumb-1.jpg" alt="">
                            <img data-imgbigurl="img/product/details/product-details-3.jpg"
                                src="img/product/details/thumb-2.jpg" alt="">
                            <img data-imgbigurl="img/product/details/product-details-5.jpg"
                                src="img/product/details/thumb-3.jpg" alt="">
                            <img data-imgbigurl="img/product/details/product-details-4.jpg"
                                src="img/product/details/thumb-4.jpg" alt="">
                        </div>
                    </div>
                </div>
                {% if product.price != 'Liênhệ' %}
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__text">
                        <h3>{{product}}</h3>
                        <img src="{{ product.image.url }}" alt="{{product}}" width="400">
                        <br><br>
                        <div class="product__details__price">Giá bán:  {{product.price|floatformat|intcomma:0}} đ</div>
                        <form method="post" action = "{% url 'cart:buy_now' product.pk %}">
                            {% csrf_token %}
                            <div class="product__details__quantity">
                                <div class="quantity">
                                    <div class="pro-qty">
                                        <input type="text"  name = "quantity" value = "1">
                                    </div>
                                </div>
                            </div>
                            <button type = "submit" class="primary-btn" name = "btnMuaHang" >Mua hàng</button>
                        </form>
                    </div>
                </div>
                {% else %}
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__text">
                        <h3>{{product}}</h3>
                        <img src="{{ product.image.url }}" alt="{{product}}" width="400">
                        <br><br>
                        <div class="product__details__price">Hết hàng</div>
                    </div>
                </div>
                {% endif %}
                <div class="col-lg-12">
                    <div class="product__details__tab">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#" role="tab"
                                    aria-selected="true">Mô tả sản phẩm</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs" role="tabpane">
                                <div class="product__details__tab__desc">
                                    <!-- <h6>Products Infomation</h6> -->
                                    <p>{{product.content|safe}}<p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Details Section End -->

    <!-- Related Product Section Begin -->
    <section class="related-product">
        <!-- <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title related__product__title">
                        <h2>Related Product</h2>
                    </div>
                </div>
            </div>

            <div class="row">
                {% for product in related_products %}
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="{{product.image.url}}">
                            <ul class="product__item__pic__hover">
                                <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                            </ul>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">{{product.name}}</a></h6>
                            <h5>{{product.price}}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div> -->
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title related__product__title">
                        <h2>Các sản phẩm liên quan</h2>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="categories__slider owl-carousel">
                    {% for product in related_products %}
                    <div class="col-lg-3">
                        <div class="product-image">
                            <a href="{% url 'store:shop_details' product.id %}">
                                <img src="{{ product.image.url }}" alt="{{ product }}">
                            </a>
                        </div>
                        <div class="product-title">
                            <center><h5><a href="{% url 'store:shop_details' product.id %}">{{product.name|remove_substr:'(Chính Hãng Digiworld)'}}</a></h5></center>
                        </div> 
                        <center><h5>{{ product.price|floatformat|intcomma:0 }} đ</h5></center>                
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
            
            
        
    </section>
    <!-- Related Product Section End -->

{% endblock %}